Mobile responsive portfolio project
lilyfrancis/MobilePortfolio pull request #4
Opened 2021-08-18 16:41 UTC by lilyfrancis

This is a responsive portfolio project by microverse to test the use of Flexbox and Positioning. In this Project I added the following:

- Setup Linters
- Index File
- A CSS style file
- A ReadMe File

2021-08-18 17:48 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Lilian Francis, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
- [ ] README is professional.
- [ ] GitHub flow is followed properly.
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +
- [ ] Please align logo and nav elements vertically in the navigation bar.  You can spot misalignment in the below screenshot. Kindly use font colors for navigation elements from the design only.
![nav](https://user-images.githubusercontent.com/35504149/129940849-4978280c-2719-454c-b5d0-83feaf261d34.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +
Please align social icons vertically. Kindly see the below screenshot for reference.
![icons](https://user-images.githubusercontent.com/35504149/129941245-cdfa16d6-fb68-422c-b5cc-45c1f432788b.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +- CSS
Mobile view does not show background images for header and sections. Kindly add background images from the design. Moreover, background images for tablet view are not the same as in the original design and on the desktop view, these pictures are not positioned the same as in the design.
![back](https://user-images.githubusercontent.com/35504149/129942473-e98f23fd-7c5b-4439-b4c5-b64e0cee8808.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +- Html
Please align the picture and text in the portfolio section. Moreover, a button is overlapping text on mobile and tablet views. Please see the below screenshot and fix the issues.
![project1](https://user-images.githubusercontent.com/35504149/129944039-cf97767d-21b8-44df-a9d6-902f55c966f4.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +
Please align buttons with the above text section horizontally. See the 
![project2](https://user-images.githubusercontent.com/35504149/129944438-64cd0fbc-34b6-4f8b-aabf-676def838118.png)
below screenshot.

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +
Please align buttons with the above text and also align the text section with pictures and change background color of `See Project` button. Kindly see the below screenshot.
![project3](https://user-images.githubusercontent.com/35504149/129944763-9e9cf4c5-83fa-4778-be47-d9a790707971.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +
Please align picture with text section and align buttons horizontally based on text their above,
![project4](https://user-images.githubusercontent.com/35504149/129945177-ab51852f-94e7-48dd-87ab-8c48e6ff49a7.png)

2021-08-18 17:48 UTC, SajjadAhmad14 commented on README.md
> +## Built With
Icons in the about me section are not aligned and scattered. Moreover, social icons are not aligned horizontally with text above them. Please see the 
![about](https://user-images.githubusercontent.com/35504149/129946289-5cedfb0b-c857-4255-83f4-dd7ae1af38fe.png)
below screenshot.

2021-08-19 17:50 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Lilian Francis, 
 ### Thank you for working on changes suggested previously :ok_hand:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-19 17:50 UTC, SajjadAhmad14 commented on index.html
> +    <header id="header">
Logo and navigation items are still not aligned vertically. Please align them vertically.

2021-08-19 17:50 UTC, SajjadAhmad14 commented on index.html
> -    <div class="about-flex-container">
Thank you for adding background images on mobile view. But they are not the same as in the design and their position is also not matching with the design. Please see the design page for mobile and make corrections accordingly. Moreover, an image is overlapping icons on the large view. Kindly see the below screenshot for reference.
![overlap](https://user-images.githubusercontent.com/35504149/130114768-69e11b7e-084f-4767-b176-70b7f99242d3.png)

2021-08-19 17:50 UTC, SajjadAhmad14 commented on index.html
> -        <h3>Tonic</h3>
The image for the project should have a full container width on medium viewport. Moreover, tech stack info is also missing. Please see the below screenshot for reference.
![project1](https://user-images.githubusercontent.com/35504149/130117427-be3cf5d8-2897-41ea-aa2f-1f2d6ee2fbcd.png)

2021-08-19 17:50 UTC, SajjadAhmad14 commented on index.html
> +              <li class="contact-item">
[ OPTIONAL ] Text area section is not the same as the design. Please see the below screenshot and correct it accordingly. 
![text-box](https://user-images.githubusercontent.com/35504149/130118465-d6619a2d-b95b-4002-9bfb-4157a8fce21d.png)

2021-08-20 13:28 UTC, Murodjon000 approved these changes
**Hi Lilian Francis 👋,** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 13:42 UTC, merged